### ISSUE TITLE
Temporary display line numbers

### ISSUE THREAD

**Issue by manuel-uberti** [emacs-vs/goto-line-preview#2]
Hi,

first of all thanks for this great package. I installed it from MELPA like this:

```emacs-lisp
(use-package goto-line-preview          ; Preview line on `goto-line'
  :ensure t
  :bind ([remap goto-line] . goto-line-preview-goto-line))
```
Since I don't have line numbers permanently enabled, would it be possible to display line numbers only on <kbd>M-g g</kbd>?

I did use to have something like this before:

```emacs-lisp
(defun mu-goto-line-with-line-numbers ()
  "Display line numbers temporarily when using `goto-line'."
  (interactive)
  (let ((display-line-numbers t))
    (call-interactively #'goto-line)))
```
But it doesn't work if I replace `#'goto-line` with `#'goto-line-preview-goto-line`.

**Comment by waymondo** [comment]
Once I discovered this package this was my first suggestion as well.

**Comment by purcell** [comment]
I'd be a bit wary of trying to make this work reliably by changing this package, because of `linum` vs. `nlinum` vs. `display-line-numbers-mode`, so I would strongly discourage this. However, making it possible to do such a thing in user config is reasonable.

I imagine that an `advice` version of the above code might work, but I haven't tested it.

**Comment by waymondo** [comment]
In my setup, here's what I've been using for the behavior @manuel-uberti is describing:

```
(defun goto-line-with-line-numbers ()
    (interactive)
    (let ((not-already-showing (or (not (boundp 'display-line-numbers-mode))
                                          (eq nil display-line-numbers-mode))))
      (display-line-numbers-mode 1)
      (unwind-protect
          (call-interactively #'goto-line)
        (when not-already-showing
          (display-line-numbers-mode -1))))))
```

Lexically binding `display-line-numbers` is a nice cleaner trick for achieving what I was doing.

Though with my solution, you can easily swap out `display-line-numbers-mode` with `linum` and the same behavior happens. I haven't tested it with `nlinum`, but I'm assuming it could still work.

My general idea of how this feature could look like would be an optional `defcustom` for `goto-line-preview-ensure-line-number-mode`. If it's defined, it ensures that this symbol's mode would be engaged for the duration `goto-line-preview-goto-line` is executing. It it wasn't enabled prior to `goto-line-preview-goto-line`, it could be ensured to get unset via `unwind-protect`.

**Comment by purcell** [comment]
Or perhaps, more idiomatically, a pair of hooks that are run when input starts and the command exits.

**Comment by manuel-uberti** [comment]
I was thinking about hooks as well, and I did try to configure this behaviour via a hook but with no effect.

**Comment by purcell** [comment]
> I was thinking about hooks as well, and I did try to configure this behaviour via a hook but with no effect.

Yeah, you'd need hooks that aren't yet there.

**Comment by manuel-uberti** [comment]
I guess we can close this, following @purcell's [suggestion](https://github.com/jcs090218/goto-line-preview/pull/10#issuecomment-469850347) solves the problem.
